services:
  reproducer:
    build: .
    command: php reproducer.php
    environment:
      OTEL_PHP_AUTOLOAD_ENABLED: true
      OTEL_TRACES_EXPORTER: console
      OTEL_METRICS_EXPORTER: console
      OTEL_LOGS_EXPORTER: console
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: test
